// Portuguese PTY Categories
#include "pty_language.h"

const char* const PTY_PORTUGUESE[] = {
  "Nenhum",
  "Noticias",
  "Assuntos Atuais",
  "Informacao",
  "Desporto",
  "Educacao",
  "Drama",
  "Culturas",
  "Ciencia",
  "Variado",
  "Musica Pop",
  "Musica Rock",
  "Facil Escuta",
  "Classicos Leves",
  "Classicos Serios",
  "Outra Musica",
  "Clima",
  "Financas",
  "Programas Infantis",
  "Assunto Social",
  "Religiao",
  "Telefone",
  "Viagem e Turismo",
  "Lazer e Hobby",
  "Jazz",
  "Country",
  "Nacional",
  "Oldies",
  "Folk",
  "Documentario",
  "Alarme",
  "Alarme!!!",
  "         "
};
