// Portuguese PTY Categories
#include "pty_language.h"

const char *const PTY_PORTUGUESE[] = {
    "NAO DEFINIDO",
    "NOTICIAS",
    "ACONTECIMENTOS",
    "INFORMACOES",
    "ESPORTES",
    "EDUCATIVO",
    "DRAMA",
    "CULTURA",
    "CIENCIA",
    "VARIEDADES",
    "MUSICA POP",
    "MUSICA ROCK",
    "MUSICA LIGEIRA",
    "MUSICA LEVE",
    "MUSICA CLASSICA",
    "OUTRAS MUSICAS",
    "METEOROLOGIA",
    "FINANCAS",
    "PROGRAMAS INFANTIS",
    "ASSUNTOS SOCIAIS",
    "RELIGIAO",
    "OUVINTE",
    "VIAGENS",
    "LAZER",
    "MUSICA JAZZ",
    "MUSICA COUNTRY",
    "MUSICA NACIONAL",
    "MUSICA OLDIES",
    "MUSICA FOLK",
    "DOCUMENTARIO",
    "ALERTA DE EMERGENCIA",
    "ALARME DE EMERGENCIA",
    "                "};
