// Spanish PTY Categories
#include "pty_language.h"

const char* const PTY_SPANISH[] = {
  "Ninguno",
  "Noticias",
  "Asuntos Actuales",
  "Informacion",
  "Deporte",
  "Educacion",
  "Drama",
  "Culturas",
  "Ciencia",
  "Discurso Variado",
  "Musica Pop",
  "Musica Rock",
  "Facil Escucha",
  "Clasicos Ligeros",
  "Clasicos Serios",
  "Otra Musica",
  "Clima",
  "Finanzas",
  "Programas Infantiles",
  "Asunto Social",
  "Religion",
  "Telefonia",
  "Viajes y Turismo",
  "Ocio y Hobby",
  "Musica Jazz",
  "Musica Country",
  "Musica Nacional",
  "Musica Oldies",
  "Musica Folk",
  "Documental",
  "Prueba de Alarma",
  "Alarma!!!",
  "                "
};
