// Spanish PTY Categories
#include "pty_language.h"

const char* const PTY_SPANISH[] = {
  /* 00 */ "NINGUNO",
  /* 01 */ "NOTICIAS",
  /* 02 */ "ACTUALIDADES",
  /* 03 */ "INFORMACION",
  /* 04 */ "DEPORTE",
  /* 05 */ "EDUCACION",
  /* 06 */ "DRAMA",
  /* 07 */ "CULTURA",
  /* 08 */ "CIENCIA",
  /* 09 */ "VARIEDADES",
  /* 10 */ "MUSICA POP",
  /* 11 */ "MUSICA ROCK",
  /* 12 */ "MUSICA SUAVE",
  /* 13 */ "CLASICA LIGERA",
  /* 14 */ "CLASICA SERIA",
  /* 15 */ "OTRAS MUSICAS",
  /* 16 */ "METEOROLOGIA",
  /* 17 */ "FINANZAS",
  /* 18 */ "PROGRAMAS INFANTILES",
  /* 19 */ "ASUNTOS SOCIALES",
  /* 20 */ "GOSPEL Y RELIGION",
  /* 21 */ "PARTICIPACION",
  /* 22 */ "VIAJES",
  /* 23 */ "OCIO",
  /* 24 */ "MUSICA JAZZ",
  /* 25 */ "MUSICA COUNTRY",
  /* 26 */ "MUSICA NACIONAL",
  /* 27 */ "MUSICA RETRO",
  /* 28 */ "MUSICA FOLK",
  /* 29 */ "DOCUMENTAL",
  /* 30 */ "PRUEBA DE ALERTA",
  /* 31 */ "ALERTA DE EMERGENCIA",
  /* 32 */ "                "
};
