// RBDS PTY Categories (NRSC-4-B North American standard)
#include "pty_language.h"

const char* const PTY_RBDS[] = {
  /* 00 */ "NONE",
  /* 01 */ "NEWS",
  /* 02 */ "INFORMATION",
  /* 03 */ "SPORTS",
  /* 04 */ "TALK",
  /* 05 */ "ROCK",
  /* 06 */ "CLASSIC ROCK",
  /* 07 */ "ADULT HITS",
  /* 08 */ "SOFT ROCK",
  /* 09 */ "TOP 40",
  /* 10 */ "COUNTRY",
  /* 11 */ "OLDIES",
  /* 12 */ "SOFT",
  /* 13 */ "NOSTALGIA",
  /* 14 */ "JAZZ",
  /* 15 */ "CLASSICAL",
  /* 16 */ "RHYTHM AND BLUES",
  /* 17 */ "SOFT R&B",
  /* 18 */ "FOREIGN LANGUAGE",
  /* 19 */ "RELIGIOUS MUSIC",
  /* 20 */ "RELIGIOUS TALK",
  /* 21 */ "PERSONALITY",
  /* 22 */ "PUBLIC",
  /* 23 */ "COLLEGE",
  /* 24 */ "UNASSIGNED",
  /* 25 */ "UNASSIGNED",
  /* 26 */ "UNASSIGNED",
  /* 27 */ "UNASSIGNED",
  /* 28 */ "UNASSIGNED",
  /* 29 */ "WEATHER",
  /* 30 */ "EMERGENCY TEST",
  /* 31 */ "EMERGENCY",
  /* 32 */ "FORRO",
  /* 33 */ "AXE MUSIC",
  /* 34 */ "SERTANEJO",
  /* 35 */ "PAGODE / SAMBA",
  /* 36 */ "MPB",
  /* 37 */ "FUNK",
  /* 38 */ "ROCK NACIONAL",
  /* 39 */ "BLUE & YELLOW",
};
