// RBDS PTY Categories (NRSC-4-B North American standard)
#include "pty_language.h"

const char* const PTY_RBDS[] = {
  /* 00 */ "None",
  /* 01 */ "News",
  /* 02 */ "Information",
  /* 03 */ "Sports",
  /* 04 */ "Talk",
  /* 05 */ "Rock",
  /* 06 */ "Classic Rock",
  /* 07 */ "Adult Hits",
  /* 08 */ "Soft Rock",
  /* 09 */ "Top 40",
  /* 10 */ "Country",
  /* 11 */ "Oldies",
  /* 12 */ "Soft",
  /* 13 */ "Nostalgia",
  /* 14 */ "Jazz",
  /* 15 */ "Classical",
  /* 16 */ "Rhythm and Blues",
  /* 17 */ "Soft R&B",
  /* 18 */ "Foreign Language",
  /* 19 */ "Religious Music",
  /* 20 */ "Religious Talk",
  /* 21 */ "Personality",
  /* 22 */ "Public",
  /* 23 */ "College",
  /* 24 */ "Unassigned",
  /* 25 */ "Unassigned",
  /* 26 */ "Unassigned",
  /* 27 */ "Unassigned",
  /* 28 */ "Unassigned",
  /* 29 */ "Weather",
  /* 30 */ "Emergency Test",
  /* 31 */ "Emergency",
  /* 32 */ "Forro",
  /* 33 */ "Axe Music",
  /* 34 */ "Sertanejo",
  /* 35 */ "Pagode / Samba",
  /* 36 */ "MPB",
  /* 37 */ "Funk",
  /* 38 */ "Rock Nacional",
  /* 39 */ "Blue & Yellow",
};
