// RBDS PTY Categories - Portuguese (NRSC-4-B North American standard)
#include "pty_language.h"

const char* const PTY_RBDS_PORTUGUESE[] = {
  /* 00 */ "NENHUM",
  /* 01 */ "NOTICIAS",
  /* 02 */ "INFORMACOES",
  /* 03 */ "ESPORTES",
  /* 04 */ "TALK RADIO",
  /* 05 */ "ROCK",
  /* 06 */ "ROCK CLASSICO",
  /* 07 */ "HITS ADULTOS",
  /* 08 */ "ROCK SUAVE",
  /* 09 */ "TOP 40",
  /* 10 */ "COUNTRY",
  /* 11 */ "OLDIES",
  /* 12 */ "MUSICA SUAVE",
  /* 13 */ "NOSTALGIA",
  /* 14 */ "JAZZ",
  /* 15 */ "MUSICA CLASSICA",
  /* 16 */ "RITMO E BLUES",
  /* 17 */ "R&B SUAVE",
  /* 18 */ "LINGUA ESTRANGEIRA",
  /* 19 */ "MUSICA RELIGIOSA",
  /* 20 */ "CONVERSA RELIGIOSA",
  /* 21 */ "PERSONALIDADE",
  /* 22 */ "PUBLICO",
  /* 23 */ "UNIVERSITARIO",
  /* 24 */ "NAO DEFINIDO",
  /* 25 */ "NAO DEFINIDO",
  /* 26 */ "NAO DEFINIDO",
  /* 27 */ "NAO DEFINIDO",
  /* 28 */ "NAO DEFINIDO",
  /* 29 */ "METEOROLOGIA",
  /* 30 */ "TESTE DE EMERGENCIA",
  /* 31 */ "EMERGENCIA",
  /* 32 */ "FORRO",
  /* 33 */ "AXE MUSIC",
  /* 34 */ "SERTANEJO",
  /* 35 */ "PAGODE / SAMBA",
  /* 36 */ "MPB",
  /* 37 */ "FUNK",
  /* 38 */ "ROCK NACIONAL",
};
