// RBDS PTY Categories - Portuguese (NRSC-4-B North American standard)
#include "pty_language.h"

const char* const PTY_RBDS_PORTUGUESE[] = {
  /* 00 */ "Nenhum",
  /* 01 */ "Noticias",
  /* 02 */ "Informacoes",
  /* 03 */ "Esportes",
  /* 04 */ "Talk Radio",
  /* 05 */ "Rock",
  /* 06 */ "Rock Classico",
  /* 07 */ "Hits Adultos",
  /* 08 */ "Rock Suave",
  /* 09 */ "Top 40",
  /* 10 */ "Country",
  /* 11 */ "Oldies",
  /* 12 */ "Musica Suave",
  /* 13 */ "Nostalgia",
  /* 14 */ "Jazz",
  /* 15 */ "Musica Classica",
  /* 16 */ "Ritmo e Blues",
  /* 17 */ "R&B Suave",
  /* 18 */ "Lingua Estrangeira",
  /* 19 */ "Musica Religiosa",
  /* 20 */ "Conversa Religiosa",
  /* 21 */ "Personalidade",
  /* 22 */ "Publico",
  /* 23 */ "Universitario",
  /* 24 */ "Nao Definido",
  /* 25 */ "Nao Definido",
  /* 26 */ "Nao Definido",
  /* 27 */ "Nao Definido",
  /* 28 */ "Nao Definido",
  /* 29 */ "Meteorologia",
  /* 30 */ "Teste de Emergencia",
  /* 31 */ "Emergencia",
  /* 32 */ "Forro",
  /* 33 */ "Axe Music",
  /* 34 */ "Sertanejo",
  /* 35 */ "Pagode / Samba",
  /* 36 */ "MPB",
  /* 37 */ "Funk",
  /* 38 */ "Rock Nacional",
  /* 39 */ "Azul Amarelo",
};
