// RBDS PTY Categories - Spanish (NRSC-4-B North American standard)
#include "pty_language.h"

const char* const PTY_RBDS_SPANISH[] = {
  /* 00 */ "NINGUNO",
  /* 01 */ "NOTICIAS",
  /* 02 */ "INFORMACION",
  /* 03 */ "DEPORTES",
  /* 04 */ "TALK RADIO",
  /* 05 */ "ROCK",
  /* 06 */ "ROCK CLASICO",
  /* 07 */ "HITS ADULTOS",
  /* 08 */ "ROCK SUAVE",
  /* 09 */ "TOP 40",
  /* 10 */ "COUNTRY",
  /* 11 */ "OLDIES",
  /* 12 */ "MUSICA SUAVE",
  /* 13 */ "NOSTALGIA",
  /* 14 */ "JAZZ",
  /* 15 */ "MUSICA CLASICA",
  /* 16 */ "RITMO Y BLUES",
  /* 17 */ "R&B SUAVE",
  /* 18 */ "IDIOMA EXTRANJERO",
  /* 19 */ "MUSICA RELIGIOSA",
  /* 20 */ "CHARLA RELIGIOSA",
  /* 21 */ "PERSONALIDAD",
  /* 22 */ "PUBLICO",
  /* 23 */ "UNIVERSITARIO",
  /* 24 */ "SIN ASIGNAR",
  /* 25 */ "SIN ASIGNAR",
  /* 26 */ "SIN ASIGNAR",
  /* 27 */ "SIN ASIGNAR",
  /* 28 */ "SIN ASIGNAR",
  /* 29 */ "CLIMA",
  /* 30 */ "PRUEBA DE EMERGENCIA",
  /* 31 */ "EMERGENCIA",
  /* 32 */ "                "
};
