// RBDS PTY Categories - Spanish (NRSC-4-B North American standard)
#include "pty_language.h"

const char* const PTY_RBDS_SPANISH[] = {
  /* 00 */ "Ninguno",
  /* 01 */ "Noticias",
  /* 02 */ "Informacion",
  /* 03 */ "Deportes",
  /* 04 */ "Talk Radio",
  /* 05 */ "Rock",
  /* 06 */ "Rock Clasico",
  /* 07 */ "Hits Adultos",
  /* 08 */ "Rock Suave",
  /* 09 */ "Top 40",
  /* 10 */ "Country",
  /* 11 */ "Oldies",
  /* 12 */ "Musica Suave",
  /* 13 */ "Nostalgia",
  /* 14 */ "Jazz",
  /* 15 */ "Musica Clasica",
  /* 16 */ "Ritmo y Blues",
  /* 17 */ "R&B Suave",
  /* 18 */ "Idioma Extranjero",
  /* 19 */ "Musica Religiosa",
  /* 20 */ "Charla Religiosa",
  /* 21 */ "Personalidad",
  /* 22 */ "Publico",
  /* 23 */ "Universitario",
  /* 24 */ "Sin Asignar",
  /* 25 */ "Sin Asignar",
  /* 26 */ "Sin Asignar",
  /* 27 */ "Sin Asignar",
  /* 28 */ "Sin Asignar",
  /* 29 */ "Clima",
  /* 30 */ "Prueba de Emergencia",
  /* 31 */ "Emergencia",
  /* 32 */ "Forro",
  /* 33 */ "Musica Axe",
  /* 34 */ "Sertanejo",
  /* 35 */ "Pagode / Samba",
  /* 36 */ "MPB",
  /* 37 */ "Funk",
  /* 38 */ "Rock Nacional",
  /* 39 */ "Azul y Amarillo",
};
