// Brazilian Radio PTY Categories - English
#include "pty_language.h"

const char* const PTY_BR_ENGLISH[] = {
  /* 00 */ "None",
  /* 01 */ "News",
  /* 02 */ "Talk / Debate",
  /* 03 */ "Sports",
  /* 04 */ "Education",
  /* 05 */ "Gospel",
  /* 06 */ "Culture / MPB",
  /* 07 */ "Pop",
  /* 08 */ "Forro",
  /* 09 */ "Sertanejo",
  /* 10 */ "Rock",
  /* 11 */ "Funk",
  /* 12 */ "Pagode / Samba",
  /* 13 */ "Bossa Nova",
  /* 14 */ "Classical",
  /* 15 */ "Jazz",
  /* 16 */ "Hip Hop / Rap",
  /* 17 */ "Electronic",
  /* 18 */ "Children",
  /* 19 */ "Religion",
  /* 20 */ "Regional",
  /* 21 */ "International",
  /* 22 */ "Oldies",
  /* 23 */ "Community",
  /* 24 */ "Public / Gov",
  /* 25 */ "University",
  /* 26 */ "Leisure",
  /* 27 */ "Documentary",
  /* 28 */ "Science / Tech",
  /* 29 */ "Social",
  /* 30 */ "Alarm Test",
  /* 31 */ "Alarm",
  /* 32 */ "Forro Pe-de-Serra",
  /* 33 */ "Axe Music",
  /* 34 */ "Sertanejo Universitario",
  /* 35 */ "Pagode / Samba",
  /* 36 */ "MPB",
  /* 37 */ "Funk Carioca",
  /* 38 */ "Rock Nacional",
  /* 39 */ "Blue & Yellow",
};
