// Brazilian Radio PTY Categories - Portuguese
#include "pty_language.h"

const char* const PTY_BR_PORTUGUESE[] = {
  /* 00 */ "Nao Definido",
  /* 01 */ "Noticias",
  /* 02 */ "Talk / Debate",
  /* 03 */ "Esportes",
  /* 04 */ "Educativo",
  /* 05 */ "Gospel",
  /* 06 */ "Cultura / MPB",
  /* 07 */ "Pop",
  /* 08 */ "Forro",
  /* 09 */ "Sertanejo",
  /* 10 */ "Rock",
  /* 11 */ "Funk",
  /* 12 */ "Pagode / Samba",
  /* 13 */ "Bossa Nova",
  /* 14 */ "Musica Classica",
  /* 15 */ "Jazz",
  /* 16 */ "Hip Hop / Rap",
  /* 17 */ "Eletronico",
  /* 18 */ "Infantil",
  /* 19 */ "Religiao",
  /* 20 */ "Regional",
  /* 21 */ "Internacional",
  /* 22 */ "Retro / Oldies",
  /* 23 */ "Comunitaria",
  /* 24 */ "Publica / Gov",
  /* 25 */ "Universitaria",
  /* 26 */ "Lazer",
  /* 27 */ "Documentario",
  /* 28 */ "Ciencia / Tec",
  /* 29 */ "Social",
  /* 30 */ "Teste de Alerta",
  /* 31 */ "Alerta",
  /* 32 */ "Forro Pe-de-Serra",
  /* 33 */ "Axe Music",
  /* 34 */ "Sertanejo Universitario",
  /* 35 */ "Pagode / Samba",
  /* 36 */ "MPB",
  /* 37 */ "Funk Carioca",
  /* 38 */ "Rock Nacional",
  /* 39 */ "Azul Amarelo",
};
