// Brazilian Radio PTY Categories - Spanish
#include "pty_language.h"

const char* const PTY_BR_SPANISH[] = {
  /* 00 */ "Ninguno",
  /* 01 */ "Noticias",
  /* 02 */ "Charla / Debate",
  /* 03 */ "Deportes",
  /* 04 */ "Educacion",
  /* 05 */ "Gospel",
  /* 06 */ "Cultura / MPB",
  /* 07 */ "Pop",
  /* 08 */ "Forro",
  /* 09 */ "Sertanejo",
  /* 10 */ "Rock",
  /* 11 */ "Funk",
  /* 12 */ "Pagode / Samba",
  /* 13 */ "Bossa Nova",
  /* 14 */ "Musica Clasica",
  /* 15 */ "Jazz",
  /* 16 */ "Hip Hop / Rap",
  /* 17 */ "Electronico",
  /* 18 */ "Infantil",
  /* 19 */ "Religion",
  /* 20 */ "Regional",
  /* 21 */ "Internacional",
  /* 22 */ "Retro / Oldies",
  /* 23 */ "Comunitaria",
  /* 24 */ "Publica / Gob",
  /* 25 */ "Universitaria",
  /* 26 */ "Ocio",
  /* 27 */ "Documental",
  /* 28 */ "Ciencia / Tec",
  /* 29 */ "Social",
  /* 30 */ "Prueba Alerta",
  /* 31 */ "Alerta",
  /* 32 */ "Forro Pe-de-Serra",
  /* 33 */ "Musica Axe",
  /* 34 */ "Sertanejo Universitario",
  /* 35 */ "Pagode / Samba",
  /* 36 */ "MPB",
  /* 37 */ "Funk Carioca",
  /* 38 */ "Rock Nacional",
  /* 39 */ "Azul y Amarillo",
};
