// Brazilian Radio PTY Categories - Spanish
#include "pty_language.h"

const char* const PTY_BR_SPANISH[] = {
  /* 00 */ "NINGUNO",
  /* 01 */ "NOTICIAS",
  /* 02 */ "CHARLA / DEBATE",
  /* 03 */ "DEPORTES",
  /* 04 */ "EDUCACION",
  /* 05 */ "GOSPEL",
  /* 06 */ "CULTURA / MPB",
  /* 07 */ "POP",
  /* 08 */ "FORRO",
  /* 09 */ "SERTANEJO",
  /* 10 */ "ROCK",
  /* 11 */ "FUNK",
  /* 12 */ "PAGODE / SAMBA",
  /* 13 */ "BOSSA NOVA",
  /* 14 */ "MUSICA CLASICA",
  /* 15 */ "JAZZ",
  /* 16 */ "HIP HOP / RAP",
  /* 17 */ "ELECTRONICO",
  /* 18 */ "INFANTIL",
  /* 19 */ "RELIGION",
  /* 20 */ "REGIONAL",
  /* 21 */ "INTERNACIONAL",
  /* 22 */ "RETRO / OLDIES",
  /* 23 */ "COMUNITARIA",
  /* 24 */ "PUBLICA / GOB",
  /* 25 */ "UNIVERSITARIA",
  /* 26 */ "OCIO",
  /* 27 */ "DOCUMENTAL",
  /* 28 */ "CIENCIA / TEC",
  /* 29 */ "SOCIAL",
  /* 30 */ "PRUEBA ALERTA",
  /* 31 */ "ALERTA",
  /* 32 */ "                "
};
