// English PTY Categories
#include "pty_language.h"

const char* const PTY_ENGLISH[] = {
  "None",
  "News",
  "Current Affairs",
  "Information",
  "Sport",
  "Education",
  "Drama",
  "Culture",
  "Science",
  "Varied",
  "Pop Music",
  "Rock Music",
  "Easy Listening",
  "Light Classical",
  "Serious Classical",
  "Other Music",
  "Weather",
  "Finance",
  "Childrens Programmes",
  "Social Affairs",
  "Religion",
  "Phone In",
  "Travel",
  "Leisure",
  "Jazz Music",
  "Country Music",
  "National Music",
  "Oldies Music",
  "Folk Music",
  "Documentary",
  "Alarm Test",
  "Alarm",
  "Forro",
  "Axe Music",
  "Sertanejo",
  "Pagode / Samba",
  "MPB",
  "Funk",
  "Rock Nacional",
  "Blue & Yellow",
};
