// Portuguese PTY Categories
#include "pty_language.h"

const char* const PTY_PORTUGUESE[] = {
  /* 00 */ "Nao Definido",
  /* 01 */ "Noticias",
  /* 02 */ "Acontecimentos",
  /* 03 */ "Informacoes",
  /* 04 */ "Esportes",
  /* 05 */ "Educativo",
  /* 06 */ "Drama",
  /* 07 */ "Cultura",
  /* 08 */ "Ciencia",
  /* 09 */ "Variedades",
  /* 10 */ "Musica Pop",
  /* 11 */ "Musica Rock",
  /* 12 */ "Musica Ligeira",
  /* 13 */ "Musica Leve",
  /* 14 */ "Musica Classica",
  /* 15 */ "Outras Musicas",
  /* 16 */ "Meteorologia",
  /* 17 */ "Financas",
  /* 18 */ "Programas Infantis",
  /* 19 */ "Assuntos Sociais",
  /* 20 */ "Religiao",
  /* 21 */ "Ouvinte",
  /* 22 */ "Viagens",
  /* 23 */ "Lazer",
  /* 24 */ "Musica Jazz",
  /* 25 */ "Musica Country",
  /* 26 */ "Musica Nacional",
  /* 27 */ "Musica Oldies",
  /* 28 */ "Musica Folk",
  /* 29 */ "Documentario",
  /* 30 */ "Teste de Alerta",
  /* 31 */ "Alerta de Emergencia",
  /* 32 */ "Forro",
  /* 33 */ "Axe Music",
  /* 34 */ "Sertanejo",
  /* 35 */ "Pagode / Samba",
  /* 36 */ "MPB",
  /* 37 */ "Funk",
  /* 38 */ "Rock Nacional",
  /* 39 */ "Azul Amarelo",
};
