// Spanish PTY Categories
#include "pty_language.h"

const char* const PTY_SPANISH[] = {
  /* 00 */ "Ninguno",
  /* 01 */ "Noticias",
  /* 02 */ "Actualidades",
  /* 03 */ "Informacion",
  /* 04 */ "Deporte",
  /* 05 */ "Educacion",
  /* 06 */ "Drama",
  /* 07 */ "Cultura",
  /* 08 */ "Ciencia",
  /* 09 */ "Variedades",
  /* 10 */ "Musica Pop",
  /* 11 */ "Musica Rock",
  /* 12 */ "Musica Suave",
  /* 13 */ "Clasica Ligera",
  /* 14 */ "Clasica Seria",
  /* 15 */ "Otras Musicas",
  /* 16 */ "Meteorologia",
  /* 17 */ "Finanzas",
  /* 18 */ "Programas Infantiles",
  /* 19 */ "Asuntos Sociales",
  /* 20 */ "Gospel y Religion",
  /* 21 */ "Participacion",
  /* 22 */ "Viajes",
  /* 23 */ "Ocio",
  /* 24 */ "Musica Jazz",
  /* 25 */ "Musica Country",
  /* 26 */ "Musica Nacional",
  /* 27 */ "Musica Oldies",
  /* 28 */ "Musica Folk",
  /* 29 */ "Documental",
  /* 30 */ "Prueba de Alerta",
  /* 31 */ "Alerta de Emergencia",
  /* 32 */ "Forro",
  /* 33 */ "Musica Axe",
  /* 34 */ "Sertanejo",
  /* 35 */ "Pagode / Samba",
  /* 36 */ "MPB",
  /* 37 */ "Funk",
  /* 38 */ "Rock Nacional",
  /* 39 */ "Azul y Amarillo",
};
