// Portuguese PTY Categories
#include "pty_language.h"

const char* const PTY_PORTUGUESE[] = {
  /* 00 */ "NAO DEFINIDO",
  /* 01 */ "NOTICIAS",
  /* 02 */ "ACONTECIMENTOS",
  /* 03 */ "INFORMACOES",
  /* 04 */ "ESPORTES",
  /* 05 */ "EDUCATIVO",
  /* 06 */ "DRAMA",
  /* 07 */ "CULTURA",
  /* 08 */ "CIENCIA",
  /* 09 */ "VARIEDADES",
  /* 10 */ "MUSICA POP",
  /* 11 */ "MUSICA ROCK",
  /* 12 */ "MUSICA LIGEIRA",
  /* 13 */ "MUSICA LEVE",
  /* 14 */ "MUSICA CLASSICA",
  /* 15 */ "OUTRAS MUSICAS",
  /* 16 */ "METEOROLOGIA",
  /* 17 */ "FINANCAS",
  /* 18 */ "PROGRAMAS INFANTIS",
  /* 19 */ "ASSUNTOS SOCIAIS",
  /* 20 */ "RELIGIAO",
  /* 21 */ "OUVINTE",
  /* 22 */ "VIAGENS",
  /* 23 */ "LAZER",
  /* 24 */ "MUSICA JAZZ",
  /* 25 */ "MUSICA COUNTRY",
  /* 26 */ "MUSICA NACIONAL",
  /* 27 */ "MUSICA OLDIES",
  /* 28 */ "MUSICA FOLK",
  /* 29 */ "DOCUMENTARIO",
  /* 30 */ "TESTE DE ALERTA",
  /* 31 */ "ALERTA DE EMERGENCIA",
  /* 32 */ "                "
};
