#include <Arduino.h>

const char* RT_OPCOES[] = {
  "Bem vindo a nossa programacao musical",
  "Agora toca para voce",
  "Sintonize mais musica do Brasil",
  "Ao vivo direto do estudio",
  "Programacao especial para voce",
  "Tome conhecimento das ultimas noticias",
  "Acompanhe os ultimos acontecimentos",
  "Esporte ao vivo neste momento",
  "Jogo emocionante acontecendo agora",
  "Seu time em primeiro lugar",
  "Gol gol gol para seu clube",
  "Placar atualizado a cada minuto",
  "Confira o tempo para seu dia",
  "Temperatura agora na sua regiao",
  "Previsao de chuvas para amanha",
  "Clima instavel na sua area",
  "Sol quente no seu municipio",
  "Madrugada fria em toda regiao",
  "Classicos que marcaram a musica",
  "Sucessos que nunca envelhecem",
  "Mpb ao vivo para seus ouvidos",
  "Musica brasileira e tradicional",
  "Ritmo do Brasil em alta",
  "Canta comigo essa melodia",
  "Danca ao som dessa batida",
  "Forra na veia direto pra voce",
  "Samba da minha terra querida",
  "Pagode do jeito que voce gosta",
  "Funk da favela em destaque",
  "Rap valente vem aqui",
  "Reggae que traz paz e amor",
  "Gospel para sua alma",
  "Louvor de coracao para voce",
  "Classica que emociona o peito",
  "Orquestra tocando sinfonia",
  "Jazz na madrugada pra viajar",
  "Blues da saudade americana",
  "Rock que mexe com a gente",
  "Metal pesado em volume alto",
  "Eletronico pra danca ate amanhecer",
  "Synthesizer da decada oitenta",
  "Musica do world ao vivo",
  "Afrobeat danca de raiz",
  "Cumbia colombiana para danca",
  "Bolero da noite romantica",
  "Balada para amigos se abracar",
  "Axe da festa junina tradicional",
  "Musica caipira de interior",
  "Sertao que chora seus amores",
  "Nordeste na veia do ouvinte",
  "Soul que toca fundo no peito",
  "Rhythm and blues para sua noite",
  "Hip hop das ruas e do coraçao",
  "Rap consciente com mensagem forte",
  "Trap da atualidade em destaque",
  "Dubstep que faz a frequencia tremer",
  "Synthpop dos anos dourados",
  "New wave que revolucionou",
  "Post rock contemplativo ao vivo",
  "Drone experimental para meditar",
  "Ambient relaxante para descanso",
  "Minimal com precisao perfeita",
  "Techno repetitivo e hipnotizante",
  "Cyber punk do futuro distopico",
  "Glitch arte sonora digital",
  "Chillout para o seu fim de tarde",
  "Deep house na madrugada",
  "Progressive que evolui",
  "Psychedelic viagem sonora",
  "Stoner rock pesado e lento",
  "Doom metal apocaliptico",
  "Grunge angst dos anos noventa",
  "Punk atitude e rebeldia",
  "Ska danca com reggae",
  "Reggaeton danca latina quente",
  "Latin fusion de ritmos tropicais",
  "Salsa para danca apaixonada",
  "Bachata romance e sensualidade",
  "Merengue ritmo caribenho",
  "Cumbia tradicio colombiana",
  "Champeta danca do caribe",
  "Timba cubana com energia",
  "Bolero balada romantica",
  "Trova trovador cubano",
  "Tropical ritmo brasileiro",
  "Punta energia de honduras",
  "Duranguense musica mexicana",
  "Banda duranguense em destaque",
  "Corridos fronterizos cantados",
  "Regional nordestino genuino",
  "Norteno acordeon e saudade",
  "Tejano cultural tex-mex",
  "Folk tradicao oral cantada",
  "Celtic magico do mundo celta",
  "World music viagem global",
  "Afrobeat danca de raiz forte",
  "Kwaito danca sul africana",
  "Gqom beat eletronico zulu",
  "Amapiano danca de piano",
  "Country narrativa americana",
  "Bluegrass banjo e cordas",
  "Outlaw country rebelliao",
  "Honky tonk bar e whisky",
  "Western musica do velho oeste",
  "Americana raizes dos eua",
  "Cowpunk punk do rancho",
  "Alternative diferente radical",
  "Shoegaze nebuloso e distante",
  "Dream pop sonho melodico",
  "Madchester danca manchester",
  "Britpop britanico moderno",
  "Britrock rock britanico",
  "Post punk ruina post disco",
  "Darkwave escuro e romantico",
  "Coldwave frio dos oitenta",
  "Goth gotico e dramatico",
  "Industrial mecanico agressivo",
  "Power metal sinfonica forte",
  "Symphonic metal orquestra pesada",
  "Operatic vozes liricas",
  "Baroque classico ornamentado",
  "Renaissance renascenca europeia",
  "Medieval instrumentos antigos",
  "Classica sinfonica eterna",
  "Fado melancolia portuguesa",
  "Tropicalia vanguarda brasileira",
  "Forró raiz nordestina danca",
  "Capoeira ritmo de luta",
  "Jongo ritmo afro ancestral",
  "Repente poesia declamada",
  "Literatura contos e historias",
  "Poesia versos belissimos",
  "Drama teatro em transmissao",
  "Documentario sobre vidas reais"
};

extern const int RT_OPCOES_COUNT = 150;
