#include <Arduino.h>

const char* RT_OPCOES[] = {
  "Bem vindo a nossa programacao musical",
  "Agora toca para voce",
  "Sintonize mais musica do Brasil",
  "Ao vivo direto do estudio",
  "Programacao especial para voce",
  "Tome conhecimento das ultimas noticias",
  "Acompanhe os ultimos acontecimentos",
  "Esporte ao vivo neste momento",
  "Jogo emocionante acontecendo agora",
  "Seu time em primeiro lugar",
  "Gol gol gol para seu clube",
  "Placar atualizado a cada minuto",
  "Confira o tempo para seu dia",
  "Temperatura agora na sua regiao",
  "Previsao de chuvas para amanha",
  "Clima instavel na sua area",
  "Sol quente no seu municipio",
  "Madrugada fria em toda regiao",
  "Classicos que marcaram a musica",
  "Sucessos que nunca envelhecem",
  "Mpb ao vivo para seus ouvidos",
  "Musica brasileira e tradicional",
  "Ritmo do Brasil em alta",
  "Canta comigo essa melodia",
  "Danca ao som dessa batida",
  "Forra na veia direto pra voce",
  "Samba da minha terra querida",
  "Pagode do jeito que voce gosta",
  "Funk da favela em destaque",
  "Rap valente vem aqui",
  "Reggae que traz paz e amor",
  "Gospel para sua alma",
  "Louvor de coracao para voce",
  "Classica que emociona o peito",
  "Orquestra tocando sinfonia",
  "Jazz na madrugada pra viajar",
  "Blues da saudade americana",
  "Rock que mexe com a gente",
  "Metal pesado em volume alto",
  "Eletronico pra danca ate amanhecer",
  "Synthesizer da decada oitenta",
  "Musica do world ao vivo",
  "Afrobeat danca de raiz",
  "Cumbia colombiana para danca",
  "Bolero da noite romantica",
  "Balada para amigos se abracar",
  "Axe da festa junina tradicional",
  "Musica caipira de interior",
  "Sertao que chora seus amores",
  "Nordeste na veia do ouvinte"
};

const int RT_OPCOES_COUNT = 50;
