// English UI strings
#include "ui_language.h"

const char* const UI_ENGLISH[] = {
  /* 00 UI_PRESS_MODE_EXIT       */ "PRESS MODE TO EXIT AND STORE",
  /* 01 UI_SET_VOLUME            */ "Set volume",
  /* 02 UI_SET_CONVERTER         */ "Set converter offset",
  /* 03 UI_SET_LOW_BANDEDGE      */ "Set low bandedge",
  /* 04 UI_SET_HIGH_BANDEDGE     */ "Set high bandedge",
  /* 05 UI_SET_LEVEL_OFFSET      */ "Set level offset",
  /* 06 UI_SET_STEREO_THRESH     */ "Set Stereo sep. threshold",
  /* 07 UI_SET_HIGHCUT_CORNER    */ "Set high cut corner freq",
  /* 08 UI_SET_HIGHCUT_THRESH    */ "Set High cut threshold",
  /* 09 UI_SET_LOW_LEVEL         */ "Set low level threshold",
  /* 10 UI_PAGE2                 */ ">> PAGE 2 >>",
  /* 11 UI_SET_BRIGHTNESS        */ "Set Display brightness",
  /* 12 UI_SET_LANGUAGE          */ "Set Language (PTY)",
  /* 13 UI_PTY_EDITOR            */ "Station PTY Editor",
  /* 14 UI_PS_EDITOR             */ "Station PS Editor",
  /* 15 UI_RT_EDITOR             */ "Station RT Editor",
  /* 16 UI_CUSTOM_RDS            */ "Custom RDS Enable",
  /* 17 UI_PAGE1_BACK            */ "<< PAGE 1",
  /* 18 UI_BACK                  */ "<< BACK",
  /* 19 UI_VOLUME_LABEL          */ "Volume:",
  /* 20 UI_CONVERTER_LABEL       */ "Converter:",
  /* 21 UI_LOW_BANDEDGE_LABEL    */ "Low bandedge:",
  /* 22 UI_HIGH_BANDEDGE_LABEL   */ "High bandedge:",
  /* 23 UI_RF_LEVEL_LABEL        */ "RF Level offset:",
  /* 24 UI_STEREO_THRESH_LABEL   */ "Stereo threshold:",
  /* 25 UI_HIGHCUT_CORNER_LABEL  */ "High Cut corner:",
  /* 26 UI_HIGHCUT_THRESH_LABEL  */ "Highcut threshold:",
  /* 27 UI_LOW_LEVEL_LABEL       */ "Low level threshold:",
  /* 28 UI_CONTRAST_LABEL        */ "Contrast:",
  /* 29 UI_LANGUAGE_LABEL        */ "Language:",
  /* 30 UI_SET_RT                */ "Set RT:",
  /* 31 UI_SET_PS                */ "Set PS:",
  /* 32 UI_SET_PTY               */ "Set PTY:",
  /* 33 UI_OFF                   */ "Off",
  /* 34 UI_ROTARY_CHANGED        */ "Rotary direction changed",
  /* 35 UI_PLEASE_RELEASE        */ "Please release button",
  /* 36 UI_SCREEN_FLIPPED        */ "Screen flipped",
  /* 37 UI_SCREEN_MUTED          */ "Screen is muted!",
  /* 38 UI_FM_AM_RECEIVER        */ "FM/AM receiver",
};
