// Spanish UI strings
#include "ui_language.h"

const char* const UI_SPANISH[] = {
  /* 00 UI_PRESS_MODE_EXIT       */ "PULSE MODE PARA SALIR Y GUARDAR",
  /* 01 UI_SET_VOLUME            */ "Ajustar volumen",
  /* 02 UI_SET_CONVERTER         */ "Ajustar offset del convertidor",
  /* 03 UI_SET_LOW_BANDEDGE      */ "Ajustar limite bajo de banda",
  /* 04 UI_SET_HIGH_BANDEDGE     */ "Ajustar limite alto de banda",
  /* 05 UI_SET_LEVEL_OFFSET      */ "Ajustar offset de nivel",
  /* 06 UI_SET_STEREO_THRESH     */ "Ajustar umbral de estereo",
  /* 07 UI_SET_HIGHCUT_CORNER    */ "Ajustar frecuencia de corte alta",
  /* 08 UI_SET_HIGHCUT_THRESH    */ "Ajustar umbral de corte alta",
  /* 09 UI_SET_LOW_LEVEL         */ "Ajustar umbral de nivel bajo",
  /* 10 UI_PAGE2                 */ ">> PAGINA 2 >>",
  /* 11 UI_SET_BRIGHTNESS        */ "Ajustar brillo de pantalla",
  /* 12 UI_SET_LANGUAGE          */ "Ajustar Idioma (PTY)",
  /* 13 UI_PTY_EDITOR            */ "Editor PTY de Estacion",
  /* 14 UI_PS_EDITOR             */ "Editor PS de Estacion",
  /* 15 UI_RT_EDITOR             */ "Editor RT de Estacion",
  /* 16 UI_CUSTOM_RDS            */ "Activar RDS Personalizado",
  /* 17 UI_STATION_EDITOR        */ "Editor de Estacion",
  /* 18 UI_PAGE1_BACK            */ "<< PAGINA 1",
  /* 18 UI_BACK                  */ "<< ATRAS",
  /* 19 UI_VOLUME_LABEL          */ "Volumen:",
  /* 20 UI_CONVERTER_LABEL       */ "Convertidor:",
  /* 21 UI_LOW_BANDEDGE_LABEL    */ "Limite bajo:",
  /* 22 UI_HIGH_BANDEDGE_LABEL   */ "Limite alto:",
  /* 23 UI_RF_LEVEL_LABEL        */ "Offset de nivel RF:",
  /* 24 UI_STEREO_THRESH_LABEL   */ "Umbral de estereo:",
  /* 25 UI_HIGHCUT_CORNER_LABEL  */ "Corte alta:",
  /* 26 UI_HIGHCUT_THRESH_LABEL  */ "Umbral de corte alta:",
  /* 27 UI_LOW_LEVEL_LABEL       */ "Umbral de nivel bajo:",
  /* 28 UI_CONTRAST_LABEL        */ "Contraste:",
  /* 29 UI_LANGUAGE_LABEL        */ "Idioma:",
  /* 30 UI_SET_RT                */ "Ajustar RT:",
  /* 31 UI_SET_PS                */ "Ajustar PS:",
  /* 32 UI_SET_PTY               */ "Ajustar PTY:",
  /* 33 UI_OFF                   */ "Apagado",
  /* 34 UI_ROTARY_CHANGED        */ "Direccion del rotativo cambiada",
  /* 35 UI_PLEASE_RELEASE        */ "Por favor, suelte el boton",
  /* 36 UI_SCREEN_FLIPPED        */ "Pantalla volteada",
  /* 37 UI_SCREEN_MUTED          */ "Pantalla silenciada!",
  /* 38 UI_FM_AM_RECEIVER        */ "Receptor FM/AM",
  /* 39 UI_SET_PI               */ "Ajustar Codigo PI:",
  /* 40 UI_ENABLE_ALL_RDS       */ "Habilitar Todos RDS",
  /* 41 UI_SET_THEME            */ "Ajustar Tema del Display",
};
