#pragma once
#include <stdint.h>

extern const char* const UI_ENGLISH[];
extern const char* const UI_PORTUGUESE[];
extern const char* const UI_SPANISH[];

enum UIStringID {
  UI_PRESS_MODE_EXIT = 0,
  UI_SET_VOLUME,
  UI_SET_CONVERTER,
  UI_SET_LOW_BANDEDGE,
  UI_SET_HIGH_BANDEDGE,
  UI_SET_LEVEL_OFFSET,
  UI_SET_STEREO_THRESH,
  UI_SET_HIGHCUT_CORNER,
  UI_SET_HIGHCUT_THRESH,
  UI_SET_LOW_LEVEL,
  UI_PAGE2,
  UI_SET_BRIGHTNESS,
  UI_SET_LANGUAGE,
  UI_PTY_EDITOR,
  UI_PS_EDITOR,
  UI_RT_EDITOR,
  UI_CUSTOM_RDS,
  UI_STATION_EDITOR,
  UI_PAGE1_BACK,
  UI_BACK,
  UI_VOLUME_LABEL,
  UI_CONVERTER_LABEL,
  UI_LOW_BANDEDGE_LABEL,
  UI_HIGH_BANDEDGE_LABEL,
  UI_RF_LEVEL_LABEL,
  UI_STEREO_THRESH_LABEL,
  UI_HIGHCUT_CORNER_LABEL,
  UI_HIGHCUT_THRESH_LABEL,
  UI_LOW_LEVEL_LABEL,
  UI_CONTRAST_LABEL,
  UI_LANGUAGE_LABEL,
  UI_SET_RT,
  UI_SET_PS,
  UI_SET_PTY,
  UI_OFF,
  UI_ROTARY_CHANGED,
  UI_PLEASE_RELEASE,
  UI_SCREEN_FLIPPED,
  UI_SCREEN_MUTED,
  UI_FM_AM_RECEIVER,
  UI_STRING_COUNT
};

const char* getUIString(int id, uint8_t language);
